import '../models/menu_item.dart';
import '../models/notification_model.dart';
import '../models/order.dart';
import '../models/user.dart';

class MockData {
  static User get mockUser => User(
        id: 'user_001',
        name: 'Arjun Sharma',
        email: 'demo@canteen.com',
        phone: '+91 98765 43210',
        rollNumber: 'CS2021001',
        avatarUrl: 'https://ui-avatars.com/api/?name=Arjun+Sharma&background=FF6B35&color=fff&size=200',
      );

  static List<MenuItem> get menuItems => [
        // Meals
        MenuItem(
          id: 'm001',
          name: 'Veg Thali',
          description: 'Dal, rice, 2 rotis, sabzi, salad & papad',
          price: 60.0,
          imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
          category: '🍱 Meals',
          isVeg: true,
          rating: 4.5,
          preparationTime: 10,
        ),
        MenuItem(
          id: 'm002',
          name: 'Chicken Biryani',
          description: 'Aromatic basmati rice with tender chicken pieces',
          price: 110.0,
          imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
          category: '🍱 Meals',
          isVeg: false,
          rating: 4.8,
          preparationTime: 15,
        ),
        MenuItem(
          id: 'm003',
          name: 'Rajma Chawal',
          description: 'Creamy kidney bean curry with steamed rice',
          price: 70.0,
          imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
          category: '🍱 Meals',
          isVeg: true,
          rating: 4.3,
          preparationTime: 8,
        ),
        MenuItem(
          id: 'm004',
          name: 'Egg Fried Rice',
          description: 'Wok-tossed rice with scrambled eggs & veggies',
          price: 80.0,
          imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
          category: '🍱 Meals',
          isVeg: false,
          rating: 4.2,
          preparationTime: 12,
        ),
        // Snacks
        MenuItem(
          id: 's001',
          name: 'Masala Dosa',
          description: 'Crispy dosa with spiced potato filling & chutneys',
          price: 45.0,
          imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
          category: '🥪 Snacks',
          isVeg: true,
          rating: 4.7,
          preparationTime: 7,
        ),
        MenuItem(
          id: 's002',
          name: 'Samosa (2 pcs)',
          description: 'Crispy fried pastry filled with spiced potatoes & peas',
          price: 20.0,
          imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
          category: '🥪 Snacks',
          isVeg: true,
          rating: 4.4,
          preparationTime: 5,
        ),
        MenuItem(
          id: 's003',
          name: 'Vada Pav',
          description: 'Mumbai-style spicy potato fritter in soft bread roll',
          price: 25.0,
          imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
          category: '🥪 Snacks',
          isVeg: true,
          rating: 4.6,
          preparationTime: 5,
        ),
        MenuItem(
          id: 's004',
          name: 'Chicken Roll',
          description: 'Spicy chicken wrapped in flaky paratha with onions',
          price: 65.0,
          imageUrl: 'https://images.unsplash.com/photo-1628294895950-9805252a4255?w=400',
          category: '🥪 Snacks',
          isVeg: false,
          rating: 4.5,
          preparationTime: 8,
        ),
        // Noodles
        MenuItem(
          id: 'n001',
          name: 'Veg Hakka Noodles',
          description: 'Stir-fried noodles with fresh vegetables & soy sauce',
          price: 75.0,
          imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400',
          category: '🍜 Noodles',
          isVeg: true,
          rating: 4.1,
          preparationTime: 10,
        ),
        MenuItem(
          id: 'n002',
          name: 'Chicken Noodle Soup',
          description: 'Warm clear broth with noodles and shredded chicken',
          price: 85.0,
          imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400',
          category: '🍜 Noodles',
          isVeg: false,
          rating: 4.3,
          preparationTime: 10,
        ),
        // Healthy
        MenuItem(
          id: 'h001',
          name: 'Garden Salad Bowl',
          description: 'Fresh greens, cucumber, tomato, corn with lemon dressing',
          price: 55.0,
          imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
          category: '🥗 Healthy',
          isVeg: true,
          rating: 4.0,
          preparationTime: 5,
        ),
        MenuItem(
          id: 'h002',
          name: 'Sprouts Chaat',
          description: 'Protein-rich mixed sprouts with tangy spices',
          price: 40.0,
          imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400',
          category: '🥗 Healthy',
          isVeg: true,
          rating: 4.2,
          preparationTime: 5,
        ),
        // Desserts
        MenuItem(
          id: 'd001',
          name: 'Gulab Jamun (2 pcs)',
          description: 'Soft milk-solid balls soaked in rose-flavored sugar syrup',
          price: 30.0,
          imageUrl: 'https://images.unsplash.com/photo-1666189143466-8ece4b9ca08c?w=400',
          category: '🍰 Desserts',
          isVeg: true,
          rating: 4.6,
          preparationTime: 3,
        ),
        MenuItem(
          id: 'd002',
          name: 'Chocolate Brownie',
          description: 'Rich fudgy brownie with chocolate chips',
          price: 45.0,
          imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400',
          category: '🍰 Desserts',
          isVeg: true,
          rating: 4.7,
          preparationTime: 2,
        ),
        // Beverages
        MenuItem(
          id: 'b001',
          name: 'Masala Chai',
          description: 'Spiced Indian tea with ginger, cardamom & milk',
          price: 15.0,
          imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
          category: '☕ Beverages',
          isVeg: true,
          rating: 4.5,
          preparationTime: 5,
        ),
        MenuItem(
          id: 'b002',
          name: 'Cold Coffee',
          description: 'Chilled blended coffee with milk & ice cream',
          price: 50.0,
          imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400',
          category: '☕ Beverages',
          isVeg: true,
          rating: 4.4,
          preparationTime: 5,
        ),
        MenuItem(
          id: 'b003',
          name: 'Fresh Lime Soda',
          description: 'Zesty lime juice with sparkling water',
          price: 30.0,
          imageUrl: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=400',
          category: '☕ Beverages',
          isVeg: true,
          rating: 4.3,
          preparationTime: 3,
        ),
        // Specials
        MenuItem(
          id: 'sp001',
          name: 'Chef\'s Special Curry',
          description: 'Today\'s rotating special curry with naan — limited stock!',
          price: 90.0,
          imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
          category: '🥘 Specials',
          isVeg: true,
          rating: 4.8,
          preparationTime: 12,
          isAvailable: true,
        ),
        MenuItem(
          id: 'sp002',
          name: 'Mutton Curry',
          description: 'Rich slow-cooked tender mutton in spiced gravy',
          price: 140.0,
          imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
          category: '🥘 Specials',
          isVeg: false,
          rating: 4.9,
          preparationTime: 20,
        ),
      ];

  static List<NotificationModel> get notifications => [
        NotificationModel(
          id: 'notif_001',
          title: '🎉 Order Ready!',
          body: 'Your Veg Thali is ready for pickup at Counter 2.',
          type: NotificationType.orderUpdate,
          isRead: false,
          timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
        ),
        NotificationModel(
          id: 'notif_002',
          title: '⏰ Order Preparing',
          body: 'Your order #ORD-2045 is being prepared. ETA: 10 mins.',
          type: NotificationType.orderUpdate,
          isRead: true,
          timestamp: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        NotificationModel(
          id: 'notif_003',
          title: '🎁 Today\'s Special Offer!',
          body: 'Get 20% off on all Beverages between 3 PM – 5 PM today.',
          type: NotificationType.offer,
          isRead: false,
          timestamp: DateTime.now().subtract(const Duration(hours: 3)),
        ),
        NotificationModel(
          id: 'notif_004',
          title: '✅ Order Placed',
          body: 'Your order #ORD-2044 has been placed successfully.',
          type: NotificationType.orderUpdate,
          isRead: true,
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
        ),
        NotificationModel(
          id: 'notif_005',
          title: '🍽️ New Item Added',
          body: 'Try our new Mutton Biryani — now available on the menu!',
          type: NotificationType.offer,
          isRead: true,
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
        ),
      ];

  static List<Order> get orderHistory => [
        Order(
          id: 'ORD-2044',
          items: const [],
          totalAmount: 155.0,
          status: OrderStatus.completed,
          placedAt: DateTime.now().subtract(const Duration(days: 1)),
          estimatedMinutes: 15,
          queuePosition: 0,
          itemsSummary: 'Chicken Biryani, Cold Coffee',
        ),
        Order(
          id: 'ORD-2040',
          items: const [],
          totalAmount: 80.0,
          status: OrderStatus.completed,
          placedAt: DateTime.now().subtract(const Duration(days: 3)),
          estimatedMinutes: 10,
          queuePosition: 0,
          itemsSummary: 'Masala Dosa, Masala Chai',
        ),
        Order(
          id: 'ORD-2031',
          items: const [],
          totalAmount: 200.0,
          status: OrderStatus.completed,
          placedAt: DateTime.now().subtract(const Duration(days: 7)),
          estimatedMinutes: 20,
          queuePosition: 0,
          itemsSummary: 'Veg Thali x2, Fresh Lime Soda',
        ),
      ];
}
